import Head from 'next/head';
import Navbar from '../componenets/Navbar';
import HomeComponent from '../componenets/Home';
import Fotter from '../componenets/Fotter';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Amazon Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HomeComponent />
      <Fotter />
    </div>
  );
}
